services:  # コンポースするサービスたち
    mcmp-master-srv:  # サービスの名前
        container_name: mcmp-master  # コンテナ名
        volumes:  # ボリュームの保持
            - ./mcmp-master/world:/root/mc-server/world # world data
            - ./mcmp-master/world_nether:/root/mc-server/world_nether # world data
            - ./mcmp-master/world_the_end:/root/mc-server/world_the_end # world data
        #     - .
        build:  # ビルド設定
            context: ./mcmp-master  # ビルドプロセスが実行されるパス。
            dockerfile: Dockerfile  # Dockerfileのパス。
            args:  # 引数
                - MULTIPAPER_MASTER_URL=${MULTIPAPER_MASTER_URL}
                - BASE_IMAGE=${BASE_IMAGE}
        ports:  # 公開ポート
            - "25565:25565"  # ホストマシンのポートとコンテナのポートをマッピング
        restart: always  # コンテナの再起動
        environment:  # 環境変数
            EULA: "true"
            TZ: "Asia/Tokyo"
        tty: true  # コンテナ内で対話的操作を可能

    mcmp-slave-srv:  # サービスの名前
        container_name: mcmp-slave  # コンテナ名
        volumes:  # ボリュームの保持
            - ./mcmp-slave/spigot.yml:/root/mcmp-slave/spigot.yml # setting file
            - ./mcmp-slave/eula.txt:/root/mcmp-slave/eula.txt # eula
        build:  # ビルド設定
            context: ./mcmp-slave  # ビルドプロセスが実行されるパス。
            dockerfile: Dockerfile  # Dockerfileのパス。
            args:  # 引数
                - MULTIPAPER_SLAVE_URL=${MULTIPAPER_SLAVE_URL}
                - BASE_IMAGE=${BASE_IMAGE}
        ports:  # ホストマシンのポートとコンテナのポートをマッピングしてポートを公開
            - "25566:25565"
        restart: always  # コンテナの再起動
        environment:  # 環境変数
            EULA: "true"
            TZ: "Asia/Tokyo"
        tty: true  # コンテナ内で対話的操作を可能