services:  # コンポースするサービスたち
    velocity-srv: # サービスの名前
        container_name: velocity  # コンテナ名
        build:  # ビルド設定
            context: ./velocity  # ビルドプロセスが実行されるパス。
            dockerfile: Dockerfile  # Dockerfileのパス。
            args:  # 引数
                - BASE_IMAGE=${BASE_IMAGE}
                - PROXY_REPOSITORY_URL=${PROXY_REPOSITORY_URL}
        volumes:  # ボリュームの保持
            - ./velocity/velocity.toml:/root/velocity/velocity.toml  # setting
            - ./velocity/forwarding.secret:/root/velocity/forwarding.secret  # key
        ports:  # ホストマシンのポートとコンテナのポートをマッピング 
            - "25565:25565" # プレイヤーはここに接続する
        restart: always  # コンテナの再起動
        environment:  # 環境変数
            EULA: "true"
            TZ: "Asia/Tokyo"
        tty: true  # コンテナ内で対話的操作を可能

    mcmp-master-srv:  # サービスの名前
        container_name: mcmp-master  # コンテナ名
        build:  # ビルド設定
            context: ./mcmp-master  # ビルドプロセスが実行されるパス。
            dockerfile: Dockerfile  # Dockerfileのパス。
            args:  # 引数
                - MULTIPAPER_MASTER_URL=${MULTIPAPER_MASTER_URL}
                - BASE_IMAGE=${BASE_IMAGE}
        volumes:  # ボリュームの保持
            - ./mcmp-master/world:/root/mc-server/world # world data
            - ./mcmp-master/world_nether:/root/mc-server/world_nether # world data
            - ./mcmp-master/world_the_end:/root/mc-server/world_the_end # world data
        # これいらんかも
        # ports:  # ホストマシンのポートとコンテナのポートをマッピング
        #     - "25565:25565"  # ここにプレイヤーが接続する -> ここにvelocityが接続する？
        restart: always  # コンテナの再起動
        environment:  # 環境変数
            EULA: "true"
            TZ: "Asia/Tokyo"
        tty: true  # コンテナ内で対話的操作を可能

    mcmp-slave-srv:  # サービスの名前
        container_name: mcmp-slave  # コンテナ名
        build:  # ビルド設定
            context: ./mcmp-slave  # ビルドプロセスが実行されるパス。
            dockerfile: Dockerfile  # Dockerfileのパス。
            args:  # 引数
                - MULTIPAPER_SLAVE_URL=${MULTIPAPER_SLAVE_URL}
                - BASE_IMAGE=${BASE_IMAGE}
        volumes:  # ボリュームの保持
            - ./mcmp-slave/eula.txt:/root/mcmp-slave/eula.txt # eula
            - ./mcmp-slave/config:/root/mcmp-slave/config # setting file paper-global.yml
            - ./mcmp-slave/server.properties:/root/mcmp-slave/server.properties # setting file
            - ./mcmp-slave/spigot.yml:/root/mcmp-slave/spigot.yml # setting file
        # これいらんかも
        # ports:  # ホストマシンのポートとコンテナのポートをマッピングしてポートを公開
        #     - "25566:25565"  # masterが接続するポート
        restart: always  # コンテナの再起動
        environment:  # 環境変数
            EULA: "true"
            TZ: "Asia/Tokyo"
        tty: true  # コンテナ内で対話的操作を可能
